config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :edit, :update]
  root "groups#index"
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_members
  has_many :users, through: :group_members
  has_many :messages

  validates :name, presence: true
end

app/models/group_member.rb
class GroupMember < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  mount_uploader :image, ImageUploader

  validates :text_or_image, presence: true

  private
  def text_or_image
    text.presence or image.presence
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_members
  has_many :groups, through: :group_members
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
    @name =
    if user_signed_in?
      current_user.name
    else
      "name"
    end
    @groups = current_user.groups if user_signed_in?
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
     redirect_to root_path, notice: "グループが作成されました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: "グループ更新成功"
    else
      render :edit
    end
  end

private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:index, :create]

  def index
    @name = current_user.name
    @groups = current_user.groups
    @messages = @group.messages.includes(:user)
      respond_to do |format|
        format.json
        format.html
      end
    @message = current_user.messages.new
  end

  def new
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      flash.now[:alert] = "メッセージを入力してください"
      render :index
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def message_params
    params.require(:message).permit(:text, :image).merge(group_id: params[:group_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").limit(5)
      respond_to do |format|
        format.json
      end
  end

  def edit
  end

  def update
    if current_user.update(account_params)
      redirect_to root_path, notice: :"ユーザー情報の更新に成功しました"
    else
      render :edit, alert: :"ユーザー情報の更新に失敗しました"
    end
  end

  private

  def account_params
    params.permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groupes/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  %form#new_chat_group.new_chat_group{"accept-charset" => "UTF-8", :action => "/chat_groups", :method => "post"}
    .chat-group-form__errors
      %h2
        1件のエラーが発生しました。
        %ul
          %li エラーです
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        %input#chat_group_name.chat-group-form__input{:name => "chat_group[name]", :placeholder => "グループ名を入力してください", :type => "text"}/
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
        /
          <div id='chat-group-users'>
          <div class='chat-group-user clearfix' id='chat-group-user-22'>
          <input name='chat_group[user_ids][]' type='hidden' value='22'>
          <p class='chat-group-user__name'>seo_kyohei</p>
          </div>
          </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/groups/_index.html.haml
.group
  .group_link
  %p.group__name= link_to group.name, group_messages_path(group)
  %p.group__info
    - if group.messages.present?
      - if group.messages.last.text.empty?
        = "画像が投稿されています"
      - else
        = group.messages.last.text
    - else
      = "まだメッセージはありません"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =form_for @group do |f|
    .chat-group-form__errors
      - if @group.errors.any?
        %h2 グループ更新失敗
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "現在のグループ名: #{@group.name}"
    .chat-group-form__field.clearfix.chat-group-form__field--left
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ type: "text", placeholder: '追加したいユーザー名を入力してください' }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバー, class: "chat-group-form__label"
      #chat-group-users.chat-group-form__field--right
        #chat-group-user-22.chat-group-user.clearfix
          %input{name: "chat_group[user_ids][]", type: "hidden", value: "user.id"}
          = f.hidden_field :user_ids, value: current_user.id, multiple: true
          %p.chat-group-user__name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
.left-contents
  .user
    %p.user__name= @name
    .user__icon
      .user__icon__mark
        = link_to new_group_path do
          %i.fa.fa-edit
      .user__icon__mark
        = link_to edit_user_registration_path do
          %i.fa.fa-cog
  = render partial: "groups/index", collection: @groups, as: :group

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =form_for @group do |f|
    .chat-group-form__errors
      - if @group.errors.any?
        %h2 グループを作成してください
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, class: "chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{for: "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{ type: "text", placeholder: '追加したいユーザー名を入力してください' }
        #user-search-result

    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :チャットメンバー, class: "chat-group-form__label"
      #chat-group-users.chat-group-form__field--right
        #chat-group-user-22.chat-group-user.clearfix
          %input{name: "chat_group[user_ids][]", type: "hidden", value: "user.id"}
          = f.hidden_field :user_ids, value: current_user.id, multiple: true
          %p.chat-group-user__name
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        =f.submit class: "chat-group-form__action-btn"

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/index.html.haml
.left-contents
  = render template: "groups/index", collection: @groups, as: :group
.right-contents
  .main-group
    %h3.main-group__name= @group.name
    %h3.main-group__member
      Members :
      - @group.users.each do |user|
        = user.name
    = link_to edit_group_path(@group) do
      .main-group__edit Edit
  .chatspace
    - @messages.each do |message|
      .chatspace-content{ "data-message-id": "#{message.id}" }
        .chatspace-content__member= message.user.name
        .chatspace-content__post-time= message.created_at
        - if message.image.present?
          .chatspace-content__chat
            = message.text
          .chatspace-content__chat
            = image_tag message.image
        - else
          .chatspace-content__chat
            = message.text
  %footer.form-box
    = form_for [@group, @message], remote: true do |f|
      = f.text_field :text, class: "form-box__text-field", placeholder: "Type a text"
      %label.form-box__picture-set
        = f.file_field :image, class: "form-box__picture-set__field"
        %i.fa.fa-file-picture-o.fa-fw
      = f.submit value: "Send", class: "form-box__button"